language: rust
rust:
  - 1.32.0
stages:
  - name: test
    if: branch != docker-build
  - name: deploy
    if: branch = docker-build

jobs:
  include:
    - stage: test
      name: int-test-osx
      os: osx
      install:
        - nvm install 10
        - nvm use 10
        - npm install -g yarn
      before_script:
        - cargo fetch --verbose
      script:
        - cd test && yarn && yarn lint || exit 1
        - cargo build || exit 1
        - INT_TEST_FLAG=true && yarn start-long -f "expiration"
      after_failure:
        - test $INT_TEST_FLAG && ./upload_logs.sh
    - stage: deploy
      name: deploy
      script: skip
      services:
        - docker
      deploy:
        provider: script
        script: bash docker_push.sh
        on:
          branch: docker-build
notifications:
  webhooks: https://webhooks.gitter.im/e/71bb03cf9abce5b02c43
cache:
  timeout: 1000
  cargo: true
  directories:
    - "$HOME/.rustup"
    - "$HOME/.cache/yarn"
    - "$TRAVIS_BUILD_DIR/test/node_modules"
before_cache:
  - rm -rf $HOME/.cargo/registry
  - rm -rf $TRAVIS_BUILD_DIR/target
git:
  depth: 50
